apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion-deployment
  labels:
    app: bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
      - name: bastion
        image: ubuntu:latest
        imagePullPolicy: Always
        args: ["sleep", "infinity"]