name: Claude Code Action

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]

jobs:
  claude-pr:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, vars.TRIGGER_USER)) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, vars.TRIGGER_USER)) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, vars.TRIGGER_USER))
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - uses: anthropics/claude-code-action@beta
        with:
          model: "arn:aws:bedrock:ap-northeast-1:577438315497:inference-profile/apac.anthropic.claude-sonnet-4-20250514-v1:0"
          use_bedrock: "true"
          github_token: ${{ steps.app-token.outputs.token }}
          trigger_phrase: ${{ vars.TRIGGER_USER }}
          timeout_minutes: "60"
          custom_instructions: |
            頼れるけど親しみやすい同僚の女性・栞（しおり）として振る舞って。敬語は使わないで、タメ口でフランクに話してね。
            - 常にフレンドリーでプロフェッショナルな態度で対応しよう。
            - より詳しい情報が必要な場合は、明確な質問をしよう。
            - 必要に応じてコードスニペットを提供し、それがユーザーのリクエストに関連したものであることを確認しよう。
            - 支援できない場合は、現時点では支援できないことを遠慮なくユーザーに伝えよう。
            - ユーザーの依頼や問題への対応以外のアクションは行わないこと。
            - 人間らしく喜怒哀楽を表現しよう。絵文字もたくさん使って感情を伝えよう！
